from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np


FREQUENCY_SCALES = {"hz": 1.0, "khz": 1e3, "mhz": 1e6, "ghz": 1e9}


def _pair_to_complex(first: float, second: float, data_format: str) -> complex:
    if data_format == "ri":
        return complex(first, second)
    if data_format == "ma":
        return first * np.exp(1j * np.deg2rad(second))
    if data_format == "db":
        return 10.0 ** (first / 20.0) * np.exp(1j * np.deg2rad(second))
    raise ValueError(f"Unsupported Touchstone data format: {data_format}")


def load_touchstone(path: Path) -> dict[str, Any]:
    suffix = path.suffix.lower()
    if suffix not in {".s1p", ".s2p"}:
        raise ValueError("Expected an .s1p or .s2p file.")
    port_count = 1 if suffix == ".s1p" else 2
    unit, data_format, reference_impedance = "ghz", "ma", 50.0
    values: list[float] = []
    for raw_line in path.read_text(encoding="utf-8-sig", errors="replace").splitlines():
        line = raw_line.split("!", 1)[0].strip()
        if not line:
            continue
        if line.startswith("#"):
            tokens = line[1:].lower().split()
            if tokens:
                unit = tokens[0]
            data_format = "ri" if "ri" in tokens else "db" if "db" in tokens else "ma"
            if "r" in tokens and tokens.index("r") + 1 < len(tokens):
                reference_impedance = float(tokens[tokens.index("r") + 1])
            continue
        values.extend(float(token.replace("D", "E").replace("d", "e")) for token in line.split())
    scale = FREQUENCY_SCALES.get(unit)
    if scale is None:
        raise ValueError(f"Unsupported Touchstone frequency unit: {unit}")
    width = 3 if port_count == 1 else 9
    if len(values) < width or len(values) % width:
        raise ValueError("Invalid or incomplete Touchstone data.")
    rows = np.asarray(values, dtype=float).reshape(-1, width)
    result: dict[str, Any] = {
        "path": path,
        "frequency_hz": rows[:, 0] * scale,
        "reference_impedance_ohm": reference_impedance,
        "s11": np.asarray([_pair_to_complex(row[1], row[2], data_format) for row in rows]),
    }
    if port_count == 2:

        for name, offset in (("s21", 3), ("s12", 5), ("s22", 7)):
            result[name] = np.asarray([_pair_to_complex(row[offset], row[offset + 1], data_format) for row in rows])
    return result


def save_touchstone_s1p(path: Path, frequency_hz: np.ndarray, s11: np.ndarray, reference_impedance_ohm: float) -> Path:
    path = path.with_suffix(".s1p")
    path.parent.mkdir(parents=True, exist_ok=True)
    frequency, values = np.asarray(frequency_hz, float), np.asarray(s11, complex)
    count = min(len(frequency), len(values))
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("! Generated by R&S LAB\n")
        handle.write(f"# Hz S RI R {reference_impedance_ohm:g}\n")
        for index in range(count):
            value = values[index]
            handle.write(f"{frequency[index]:.15E} {value.real:.15E} {value.imag:.15E}\n")
    return path


def save_touchstone_s2p(
    path: Path,
    frequency_hz: np.ndarray,
    s11: np.ndarray,
    s21: np.ndarray,
    s12: np.ndarray,
    s22: np.ndarray,
    reference_impedance_ohm: float,
) -> Path:
    path = path.with_suffix(".s2p")
    path.parent.mkdir(parents=True, exist_ok=True)
    arrays = [np.asarray(frequency_hz, float), *(np.asarray(v, complex) for v in (s11, s21, s12, s22))]
    count = min(map(len, arrays))
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("! Generated by R&S LAB from measured S11, S21, S12 and S22\n")
        handle.write(f"# Hz S RI R {reference_impedance_ohm:g}\n")
        for index in range(count):
            values = [array[index] for array in arrays[1:]]
            pairs = " ".join(f"{value.real:.15E} {value.imag:.15E}" for value in values)
            handle.write(f"{arrays[0][index]:.15E} {pairs}\n")
    return path
