from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np


FREQUENCY_SCALES = {
    "hz": 1.0,
    "khz": 1e3,
    "mhz": 1e6,
    "ghz": 1e9,
}


def _pair_to_complex(first: float, second: float, data_format: str) -> complex:
    if data_format == "ri":
        return complex(first, second)
    if data_format == "ma":
        return first * np.exp(1j * np.deg2rad(second))
    if data_format == "db":
        return 10.0 ** (first / 20.0) * np.exp(1j * np.deg2rad(second))
    raise ValueError(f"Unsupported Touchstone data format: {data_format}")


def load_touchstone(path: Path) -> dict[str, Any]:
    suffix = path.suffix.lower()
    if suffix not in {".s1p", ".s2p"}:
        raise ValueError("Expected an .s1p or .s2p file.")
    port_count = 1 if suffix == ".s1p" else 2
    unit = "ghz"
    data_format = "ma"
    reference_impedance = 50.0
    values: list[float] = []
    for raw_line in path.read_text(encoding="utf-8-sig", errors="replace").splitlines():
        line = raw_line.split("!", 1)[0].strip()
        if not line:
            continue
        if line.startswith("#"):
            tokens = line[1:].lower().split()
            if tokens:
                unit = tokens[0]
            if "ri" in tokens:
                data_format = "ri"
            elif "db" in tokens:
                data_format = "db"
            elif "ma" in tokens:
                data_format = "ma"
            if "r" in tokens:
                index = tokens.index("r")
                if index + 1 < len(tokens):
                    reference_impedance = float(tokens[index + 1])
            continue
        values.extend(float(token.replace("D", "E").replace("d", "e")) for token in line.split())
    scale = FREQUENCY_SCALES.get(unit)
    if scale is None:
        raise ValueError(f"Unsupported Touchstone frequency unit: {unit}")
    width = 3 if port_count == 1 else 9
    if len(values) < width or len(values) % width:
        raise ValueError("Invalid or incomplete Touchstone data.")
    rows = np.asarray(values, dtype=float).reshape(-1, width)
    frequency_hz = rows[:, 0] * scale
    result: dict[str, Any] = {
        "path": path,
        "frequency_hz": frequency_hz,
        "reference_impedance_ohm": reference_impedance,
    }
    result["s11"] = np.asarray([
        _pair_to_complex(row[1], row[2], data_format) for row in rows
    ], dtype=complex)
    if port_count == 2:
        result["s21"] = np.asarray([
            _pair_to_complex(row[3], row[4], data_format) for row in rows
        ], dtype=complex)
        result["s12"] = np.asarray([
            _pair_to_complex(row[5], row[6], data_format) for row in rows
        ], dtype=complex)
        result["s22"] = np.asarray([
            _pair_to_complex(row[7], row[8], data_format) for row in rows
        ], dtype=complex)
    return result


def save_touchstone_s1p(
    path: Path,
    frequency_hz: np.ndarray,
    s11: np.ndarray,
    reference_impedance_ohm: float,
) -> Path:
    path = path.with_suffix(".s1p")
    path.parent.mkdir(parents=True, exist_ok=True)
    frequency = np.asarray(frequency_hz, dtype=float)
    values = np.asarray(s11, dtype=complex)
    count = min(len(frequency), len(values))
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("! Generated by nanoVNA LAB\n")
        handle.write(f"# Hz S RI R {reference_impedance_ohm:g}\n")
        for index in range(count):
            value = values[index]
            handle.write(
                f"{frequency[index]:.15E} {value.real:.15E} {value.imag:.15E}\n"
            )
    return path


def save_touchstone_s2p(
    path: Path,
    frequency_hz: np.ndarray,
    s11: np.ndarray,
    s21: np.ndarray,
    reference_impedance_ohm: float,
) -> Path:
    path = path.with_suffix(".s2p")
    path.parent.mkdir(parents=True, exist_ok=True)
    frequency = np.asarray(frequency_hz, dtype=float)
    reflection = np.asarray(s11, dtype=complex)
    transmission = np.asarray(s21, dtype=complex)
    count = min(len(frequency), len(reflection), len(transmission))
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("! Generated by nanoVNA LAB\n")
        handle.write("! S12=S21 and S22=S11 are assumed because the device provides S11 and S21 only\n")
        handle.write(f"# Hz S RI R {reference_impedance_ohm:g}\n")
        for index in range(count):
            s11_value = reflection[index]
            s21_value = transmission[index]
            handle.write(
                f"{frequency[index]:.15E} "
                f"{s11_value.real:.15E} {s11_value.imag:.15E} "
                f"{s21_value.real:.15E} {s21_value.imag:.15E} "
                f"{s21_value.real:.15E} {s21_value.imag:.15E} "
                f"{s11_value.real:.15E} {s11_value.imag:.15E}\n"
            )
    return path
